DELETE FROM rss_list;
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Africa News', 'https://www.africanews.com/feed/rss?themes=news', 0, 100, 'Africa');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Mediapart', 'https://www.mediapart.fr/articles/feed', 0, 2, 'France');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'МФД', 'https://mfd.ru/rss/news/handler.ashx', 1, 56, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Наука и жизнь', 'https://www.nkj.ru/rss/', 1, 9, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Habr', 'https://habr.com/ru/rss/articles/?fl=ru&limit=100', 1, 1, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Газета.ру', 'https://www.gazeta.ru/export/rss/first.xml', 1, 7, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Атон', 'https://www.agroinvestor.ru/feed/public-agronews.xml', 1, 55, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Гарант', 'http://rss.garant.ru/news/', 1, 4, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Esquire', 'https://esquire.ru/out/feedburner.xml', 1, 13, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Финам', 'https://www.finam.ru/analysis/conews/rsspoint', 1, 53, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Финмаркет', 'http://www.finmarket.ru/rss/mainnews.asp', 1, 110, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Forbes', 'https://www.forbes.ru/newrss.xml', 1, 16, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Lenta', 'https://lenta.ru/rss', 1, 3, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Life', 'https://life.ru/xml/feed.xml?hashtag=%D0%BD%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D0%B8', 1, 5, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Коммерсант', 'https://www.kommersant.ru/RSS/news.xml', 1, 11, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'C-News', 'https://cnews.ru/inc/rss/news.xml', 1, 10, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'РБК', 'http://static.feed.rbc.ru/rbc/logical/footer/news.rss', 1, 6, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'France24', 'https://www.france24.com/en/rss', 0, 3, 'France');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Kieler Nachrichten', 'https://www.kn-online.de/arc/outboundfeeds/rss/', 0, 3, 'Germany');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Spiegel', 'https://www.spiegel.de/international/index.rss', 0, 1, 'Germany');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Zeit', 'http://newsfeed.zeit.de/index', 0, 2, 'Germany');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Daily Mail', 'https://www.dailymail.co.uk/home/index.rss', 0, 100, 'UK');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'New York Times', 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml', 0, 1, 'USA');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Daily Mirror', 'https://www.mirror.co.uk/?service=rss', 0, 1, 'UK');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'The Independent', 'http://www.independent.co.uk/rss', 0, 100, 'UK');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Mail.ру', 'https://news.mail.ru/rss/90/', 1, 1, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, '3D News', 'https://3dnews.ru/hardware-news/rss', 1, 100, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country) VALUES (1254981379, 'Tass', 'https://tass.ru/rss/v2.xml?sections=MjU%3D', 1, 100, 'Russia');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country, parser_type) VALUES (1254981379, 'Актуальные новости', 'https://news2.ru/rss.php', 1, 100, 'Russia', 'no-rss');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country, parser_type) VALUES (1254981379, 'Взгляд', 'https://vz.ru/rss.xml', 1, 100, 'Russia', 'no-rss');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country, parser_type) VALUES (1254981379, 'Metro', 'https://www.metronews.ru/services/materials/press/yandex/', 1, 100, 'Russia', 'no-rss');
INSERT INTO rss_list (chat_id, source, link, is_active, position, country, parser_type) VALUES (1254981379, 'РИА Новости', 'https://ria.ru/export/rss2/index.xml', 1, 100, 'Russia', 'no-rss');
-- INSERT INTO rss_list (chat_id, source, link, is_active, position, country, parser_type) VALUES (1254981379, '', '', 1, 100, 'Russia', 'no-rss');

DELETE FROM top_ten_excluded;
INSERT INTO top_ten_excluded (word) VALUES ('при');
INSERT INTO top_ten_excluded (word) VALUES ('так');
INSERT INTO top_ten_excluded (word) VALUES ('или');
INSERT INTO top_ten_excluded (word) VALUES ('про');
INSERT INTO top_ten_excluded (word) VALUES ('вот');
INSERT INTO top_ten_excluded (word) VALUES ('для');
INSERT INTO top_ten_excluded (word) VALUES ('эти');
INSERT INTO top_ten_excluded (word) VALUES ('the');
INSERT INTO top_ten_excluded (word) VALUES ('как');
INSERT INTO top_ten_excluded (word) VALUES ('под');
INSERT INTO top_ten_excluded (word) VALUES ('над');
INSERT INTO top_ten_excluded (word) VALUES ('что');
INSERT INTO top_ten_excluded (word) VALUES ('из-за');
INSERT INTO top_ten_excluded (word) VALUES ('ему');
INSERT INTO top_ten_excluded (word) VALUES ('тот');
INSERT INTO top_ten_excluded (word) VALUES ('этот');
INSERT INTO top_ten_excluded (word) VALUES ('дня');
INSERT INTO top_ten_excluded (word) VALUES ('дни');
INSERT INTO top_ten_excluded (word) VALUES ('без');
INSERT INTO top_ten_excluded (word) VALUES ('нас');
INSERT INTO top_ten_excluded (word) VALUES ('них');
INSERT INTO top_ten_excluded (word) VALUES ('год');
INSERT INTO top_ten_excluded (word) VALUES ('года');
INSERT INTO top_ten_excluded (word) VALUES ('году');
INSERT INTO top_ten_excluded (word) VALUES ('час');
INSERT INTO top_ten_excluded (word) VALUES ('она');
INSERT INTO top_ten_excluded (word) VALUES ('сама');
INSERT INTO top_ten_excluded (word) VALUES ('xix');
INSERT INTO top_ten_excluded (word) VALUES ('xxi');
INSERT INTO top_ten_excluded (word) VALUES ('всех');
INSERT INTO top_ten_excluded (word) VALUES ('всё');
INSERT INTO top_ten_excluded (word) VALUES ('все');
INSERT INTO top_ten_excluded (word) VALUES ('наш');
INSERT INTO top_ten_excluded (word) VALUES ('еще');
INSERT INTO top_ten_excluded (word) VALUES ('ещё');
INSERT INTO top_ten_excluded (word) VALUES ('уже');
INSERT INTO top_ten_excluded (word) VALUES ('чем');
INSERT INTO top_ten_excluded (word) VALUES ('либо');
INSERT INTO top_ten_excluded (word) VALUES ('его');
INSERT INTO top_ten_excluded (word) VALUES ('тыс');
INSERT INTO top_ten_excluded (word) VALUES ('после');
INSERT INTO top_ten_excluded (word) VALUES ('млрд');
INSERT INTO top_ten_excluded (word) VALUES ('2023');
INSERT INTO top_ten_excluded (word) VALUES ('2024');
INSERT INTO top_ten_excluded (word) VALUES ('свой');