create table if not exists users
(
    chat_id       bigint,
    first_name    varchar(64),
    last_name     varchar(64),
    user_name     varchar(32),
    registered_at timestamp,
    is_active     integer default 1,
    is_premium    integer default 0,
    prem_exp_date date,
    description   varchar(256),
    constraint pk_users_chat_id primary key (chat_id)
);
comment on table users is 'Список пользователей Telegram';
comment on column users.prem_exp_date is 'Дата окончания срока действия Premium';

create table if not exists settings
(
    chat_id        bigint,
    period         varchar(8) default '1h'::character varying,
    period_all     varchar(8) default '1h'::character varying,
    scheduler      varchar(3) default 'on'::character varying,
    start          time       default '10:00'::time,
    excluded       varchar(3) default 'on'::character varying,
    lang           varchar(2) default 'ru'::character varying,
    period_top     varchar(8) default '12h'::character varying,
    jaro_winkler   varchar(3) default 'on'::character varying,
    premium_search varchar(3) default 'on'::character varying,
    message_theme  integer    default 1,
    constraint fk_settings_chat_id foreign key (chat_id) references users (chat_id) on delete cascade
);
comment on column settings.period is 'Глубина поиска по ключевым словам';
comment on column settings.period_all is 'Глубина поиска всех новостей';
comment on column settings.scheduler is 'Включение/выключение автопоиска (on/off)';
comment on column settings.start is 'Время старта автопоиска по ключевым словам. Исходя из него формируется список часов старта поиска.';
comment on column settings.excluded is 'Включение/выключение фильтрации заголовков, содержащих слова-исключения (on/off)';
comment on column settings.lang is 'Язык интерфейса';
comment on column settings.period_top is 'Глубина поиска для Топ 20';
comment on column settings.jaro_winkler is 'Проверка схожести слов методом Джаро-Винклера. Находит общий корень похожих слов с целью исключения дубликатов.';

create table if not exists rss_list
(
    id          bigint generated by default as identity primary key,
    chat_id     bigint,
    source      varchar(64),
    link        varchar(512),
    is_active   integer    default 1,
    position    integer    default 100,
    add_date    timestamp  default current_timestamp::timestamp,
    country     varchar(128),
    parser_type varchar(8) default 'rss'::character varying,
    lang        varchar(2) default 'ru'::character varying,
    constraint ui_rss_list_chat_id_link unique (chat_id, link)
);
comment on table rss_list is 'Список новостных источников';
comment on column rss_list.chat_id is 'Для функционала когда у каждого пользователя будет свой список источников';
comment on column rss_list.position is 'Порядковый номер источника';
comment on column rss_list.country is 'Страна источника новостей';
comment on column rss_list.parser_type is '"rss" для RomeTools, "no-rss" - остальные источники';

create table if not exists keywords
(
    id       bigint generated by default as identity primary key,
    chat_id  bigint,
    keyword  varchar(64),
    add_date timestamp default current_timestamp::timestamp,
    constraint fk_keywords_chat_id foreign key (chat_id) references users (chat_id) on delete cascade,
    constraint ui_keywords_chat_id_link unique (chat_id, keyword)
);
comment on table keywords is 'Ключевые слова';

create table if not exists excluding_terms
(
    id       bigint generated by default as identity primary key,
    word     varchar(32),
    chat_id  bigint,
    add_date timestamp default current_timestamp::timestamp,
    constraint fk_excluding_terms_chat_id foreign key (chat_id) references users (chat_id) on delete cascade,
    constraint ui_excluding_terms unique (chat_id, word)
);
comment on table excluding_terms is 'Слова-исключения для отсева заголовков при полном поиске';

create table if not exists showed_news
(
    id         bigint generated by default as identity primary key,
    chat_id    bigint,
    title_hash varchar(10),
    type       integer,
    add_date   timestamp default current_timestamp::timestamp,
    constraint fk_headlines_chat_id foreign key (chat_id) references users (chat_id) on delete cascade,
    constraint ui_showed_news unique (chat_id, title_hash, type)
);
comment on table showed_news is 'Запись хэша новостей, которые были показаны, для быстрого отсева при следующем поиске';
comment on column showed_news.type is 'Тип поиска: 2 - поиск по ключевым словам, 4 - полный поиск';

create table if not exists news_list
(
    id         bigint generated by default as identity primary key,
    source     varchar(64),
    title      varchar(512),
    title_hash varchar(10),
    link       varchar(512),
    pub_date   timestamp,
    add_date   timestamp default current_timestamp::timestamp,
    constraint ui_news_list unique (title_hash)
);
create index if not exists news_list_add_date_index on news_list (pub_date);
-- create index if not exists news_list_pub_date_index on news_list (pub_date);
comment on table news_list is 'Все сохранённые новости';

create table if not exists top_excluded
(
    id       bigint generated by default as identity primary key,
    word     varchar(32),
    chat_id  bigint,
    add_date timestamp default current_timestamp::timestamp,
    constraint fk_top_excluded_chat_id foreign key (chat_id) references users (chat_id) on delete cascade,
    constraint ui_top_excluded unique (word, chat_id)
);
comment on table top_excluded is 'Слова исключённые из показа в Топ 20';

create table if not exists admin
(
    id       bigint generated by default as identity primary key,
    key      varchar(64)
        constraint ui_admin unique,
    value    varchar(256),
    add_date timestamp default current_timestamp::timestamp
);
comment on table admin is 'Таблица включения/выключения фич и другие ключ-значения';

create table rss_excluding
(
    id          bigint generated by default as identity primary key,
    chat_id     bigint,
    source_name varchar(64),
    add_date    timestamp default (CURRENT_TIMESTAMP)::timestamp without time zone,
    constraint ui_rss_excluding unique (chat_id, source_name)
);
comment on table rss_excluding is 'Исключённые источники пользователя';

create table category
(
    id          bigint generated by default as identity primary key,
    category    varchar(64),
    word        varchar(64),
    constraint ui_category_words unique (category, word)
);
comment on table category is 'Слова для быстрого исключения из полного поиска по категориям';